name: Creating and Running a Test Case
on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: perform test
        uses: actions/checkup@v2
      - name: Use node.js
        uses: actions/setup-node
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: test results
        uses: actions/uploads-artifact@v2
        with:
          name: test-results
          path: test_results.txt


